name: movie_pojo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  hive :
  hive_flutter :
  supabase_flutter :
  http :
  bloc :
  flutter_bloc :
  google_sign_in :
  easy_localization :
  flutter_screenutil :
  google_fonts :
  fluttertoast :
  loader_overlay :
  animate_do :
  animated_toggle_switch :
  cached_network_image :
  connectivity_plus :

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/logos/
  - assets/translations/
  - assets/icons/
